CREATE TABLE marca (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_cadastro timestamp NOT NULL,
    data_alteracao timestamp,
    nome varchar(100) NOT NULL UNIQUE,
    ativo boolean NOT NULL DEFAULT true,
    CONSTRAINT ck_marca_nome CHECK (char_length(trim(nome)) BETWEEN 2 AND 100)
);
CREATE UNIQUE INDEX uk_marca_nome_normalizado ON marca (lower(nome));

CREATE TABLE mouse (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_cadastro timestamp NOT NULL,
    data_alteracao timestamp,
    marca_id bigint NOT NULL REFERENCES marca(id),
    sku varchar(50) NOT NULL UNIQUE,
    nome varchar(150) NOT NULL,
    descricao text NOT NULL,
    cor varchar(50) NOT NULL,
    preco numeric(12,2) NOT NULL CHECK (preco > 0),
    quantidade_estoque integer NOT NULL CHECK (quantidade_estoque >= 0),
    dpi_maximo integer NOT NULL CHECK (dpi_maximo > 0),
    quantidade_botoes integer NOT NULL CHECK (quantidade_botoes > 0),
    peso_gramas numeric(8,2) NOT NULL CHECK (peso_gramas > 0),
    ativo boolean NOT NULL DEFAULT true,
    versao bigint NOT NULL DEFAULT 0 CHECK (versao >= 0),
    CONSTRAINT ck_mouse_sku CHECK (sku = upper(trim(sku)) AND sku ~ '^[A-Z0-9][A-Z0-9._-]*$'),
    CONSTRAINT ck_mouse_nome CHECK (char_length(trim(nome)) BETWEEN 2 AND 150),
    CONSTRAINT ck_mouse_descricao CHECK (char_length(trim(descricao)) BETWEEN 1 AND 5000),
    CONSTRAINT ck_mouse_cor CHECK (char_length(trim(cor)) BETWEEN 1 AND 50)
);
CREATE INDEX ix_mouse_marca ON mouse(marca_id);

CREATE TABLE mouse_conexao (
    mouse_id bigint NOT NULL REFERENCES mouse(id) ON DELETE CASCADE,
    tipo_conexao integer NOT NULL CHECK (tipo_conexao IN (1, 2, 3)),
    PRIMARY KEY (mouse_id, tipo_conexao)
);
