CREATE TABLE estado (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 data_cadastro timestamp NOT NULL, data_alteracao timestamp,
 nome varchar(100) NOT NULL, sigla varchar(2) NOT NULL UNIQUE CHECK (sigla ~ '^[A-Z]{2}$')
);
INSERT INTO estado (sigla, nome, data_cadastro) VALUES
('AC', 'Acre', CURRENT_TIMESTAMP),
('AL', 'Alagoas', CURRENT_TIMESTAMP),
('AP', 'Amapá', CURRENT_TIMESTAMP),
('AM', 'Amazonas', CURRENT_TIMESTAMP),
('BA', 'Bahia', CURRENT_TIMESTAMP),
('CE', 'Ceará', CURRENT_TIMESTAMP),
('DF', 'Distrito Federal', CURRENT_TIMESTAMP),
('ES', 'Espírito Santo', CURRENT_TIMESTAMP),
('GO', 'Goiás', CURRENT_TIMESTAMP),
('MA', 'Maranhão', CURRENT_TIMESTAMP),
('MT', 'Mato Grosso', CURRENT_TIMESTAMP),
('MS', 'Mato Grosso do Sul', CURRENT_TIMESTAMP),
('MG', 'Minas Gerais', CURRENT_TIMESTAMP),
('PA', 'Pará', CURRENT_TIMESTAMP),
('PB', 'Paraíba', CURRENT_TIMESTAMP),
('PR', 'Paraná', CURRENT_TIMESTAMP),
('PE', 'Pernambuco', CURRENT_TIMESTAMP),
('PI', 'Piauí', CURRENT_TIMESTAMP),
('RJ', 'Rio de Janeiro', CURRENT_TIMESTAMP),
('RN', 'Rio Grande do Norte', CURRENT_TIMESTAMP),
('RS', 'Rio Grande do Sul', CURRENT_TIMESTAMP),
('RO', 'Rondônia', CURRENT_TIMESTAMP),
('RR', 'Roraima', CURRENT_TIMESTAMP),
('SC', 'Santa Catarina', CURRENT_TIMESTAMP),
('SP', 'São Paulo', CURRENT_TIMESTAMP),
('SE', 'Sergipe', CURRENT_TIMESTAMP),
('TO', 'Tocantins', CURRENT_TIMESTAMP);
CREATE TABLE municipio (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 data_cadastro timestamp NOT NULL, data_alteracao timestamp,
 nome varchar(150) NOT NULL, codigo_ibge varchar(7) NOT NULL UNIQUE CHECK (codigo_ibge ~ '^[0-9]{7}$'),
 estado_id bigint NOT NULL REFERENCES estado(id)
);
CREATE INDEX ix_municipio_estado ON municipio(estado_id);
CREATE TABLE cliente (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 data_cadastro timestamp NOT NULL, data_alteracao timestamp,
 nome varchar(100) NOT NULL CHECK (char_length(trim(nome)) BETWEEN 2 AND 100),
 email varchar(254) NOT NULL UNIQUE CHECK (email = lower(trim(email))),
 cep varchar(8) NOT NULL CHECK (cep ~ '^[0-9]{8}$'),
 logradouro varchar(200) NOT NULL CHECK (char_length(trim(logradouro)) > 0),
 bairro varchar(100) NOT NULL CHECK (char_length(trim(bairro)) > 0),
 numero varchar(20) NOT NULL CHECK (char_length(trim(numero)) > 0),
 complemento varchar(100), municipio_id bigint NOT NULL REFERENCES municipio(id)
);
CREATE INDEX ix_cliente_municipio ON cliente(municipio_id);
